import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

export const vendite = sqliteTable("vendite", {
  vendita_numero_vendita: text("vendita_numero_vendita").primaryKey(),
  data_attivazione: integer("data_attivazione", { mode: "timestamp" }),
  vendita_stato: text("vendita_stato"),
  vendita_data_inizio: integer("vendita_data_inizio", { mode: "timestamp" }),
  vendita_data_fine: integer("vendita_data_fine", { mode: "timestamp" }),
  listino_nome: text("listino_nome"),
  listino_tipologia_vendita: text("listino_tipologia_vendita"),
  vendita_numero_scontrino: text("vendita_numero_scontrino"),
  vendita_data_scontrino: integer("vendita_data_scontrino", { mode: "timestamp" }),
  vendita_totale_importo_scontrino: text("vendita_totale_importo_scontrino"),
  vendita_codice_lotteria: text("vendita_codice_lotteria"),
  vendita_contanti: text("vendita_contanti"),
  vendita_pagamenti_elettronici: text("vendita_pagamenti_elettronici"),
  vendita_bonifici: text("vendita_bonifici"),
  vendita_assegni: text("vendita_assegni"),
  vendita_buoni: text("vendita_buoni"),
  vendita_coupon: text("vendita_coupon"),
  vendita_altri_pagamenti: text("vendita_altri_pagamenti"),
  vendita_non_scontrinato: text("vendita_non_scontrinato"),
  vendita_non_riscosso: text("vendita_non_riscosso"),
  vendita_dettaglio_codice_interno: text("vendita_dettaglio_codice_interno"),
  vendita_id_istanza: integer("vendita_id_istanza"),
  vendita_brand: text("vendita_brand"),
  vendita_fornitore: text("vendita_fornitore"),
  vendita_info1: text("vendita_info1"),
  vendita_info2: text("vendita_info2"),
  vendita_info3: text("vendita_info3"),
  vendita_info4: text("vendita_info4"),
  vendita_info5: text("vendita_info5"),
  vendita_categoria: text("vendita_categoria"),
  vendita_tipologia: text("vendita_tipologia"),
  codice_prodotto: text("codice_prodotto"),
  codice_ean: text("codice_ean"),
  codice_univoco: text("codice_univoco"),
  descrizione_prodotto: text("descrizione_prodotto"),
  canone: text("canone"),
  prezzo: text("prezzo"),
  prezzo_iva_esclusa: text("prezzo_iva_esclusa"),
  costo: text("costo"),
  sconto: text("sconto"),
  sconto_iva_esclusa: text("sconto_iva_esclusa"),
  anticipo: text("anticipo"),
  importo_finanziato: text("importo_finanziato"),
  credito: text("credito"),
  importo_ndc: text("importo_ndc"),
  importo_imponibile: text("importo_imponibile"),
  iva_aliquota: integer("iva_aliquota"),
  iva_natura_iva: text("iva_natura_iva"),
  iva_importo: text("iva_importo"),
  importo_scontrino: text("importo_scontrino"),
  cliente_codice_interno: text("cliente_codice_interno"),
  cliente_tipo: text("cliente_tipo"),
  cliente_nome: text("cliente_nome"),
  cliente_email: text("cliente_email"),
  cliente_piva: text("cliente_piva"),
  cliente_telefono1: text("cliente_telefono1"),
  cliente_telefono2: text("cliente_telefono2"),
  cliente_telefono3: text("cliente_telefono3"),
  cliente_telefono4: text("cliente_telefono4"),
  codice_cliente_wind: text("codice_cliente_wind"),
  campagna_nome: text("campagna_nome"),
  campagna_data_inizio: text("campagna_data_inizio"),
  campagna_data_fine: text("campagna_data_fine"),
  campagna_campaign_management: text("campagna_campaign_management"),
  ragione_sociale_codice_interno: text("ragione_sociale_codice_interno"),
  ragione_sociale_nominativo: text("ragione_sociale_nominativo"),
  negozio_codice_interno: text("negozio_codice_interno"),
  negozio_nominativo: text("negozio_nominativo"),
  negozio_indirizzo: text("negozio_indirizzo"),
  negozio_civico: text("negozio_civico"),
  negozio_cap: text("negozio_cap"),
  negozio_città: text("negozio_città"),
  negozio_provincia: text("negozio_provincia"),
  negozio_email: text("negozio_email"),
  negozio_telefono: text("negozio_telefono"),
  negozio_codice_operatore_wind: text("negozio_codice_operatore_wind"),
  negozio_codice_operatore_vodafone: text("negozio_codice_operatore_vodafone"),
  negozio_codice_operatore_tim: text("negozio_codice_operatore_tim"),
  negozio_codice_operatore_fastweb: text("negozio_codice_operatore_fastweb"),
  negozio_codice_operatore_sky: text("negozio_codice_operatore_sky"),
  venditore_nominativo: text("venditore_nominativo"),
  vendita_note: text("vendita_note"),
});

export const VenditaSchema = createSelectSchema(vendite);
export const CreateVenditaSchema = createInsertSchema(vendite);
export const UpdateVenditaSchema = CreateVenditaSchema.partial().omit({
  vendita_numero_vendita: true,
});
